spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: ddx-auth
        uri: lb://ddx-auth
        predicates:
        - Path=/ddx/auth/**
        filters:
          - name: GatewayRequestRateLimiter
            args:
              # 使用SpEL名称引用Bean，与上面新建的RequestRateLimiterConfig类中的bean的name相同
              key-resolver: '#{@apiKeyResolver}'
              #令牌桶每秒填充平均速率
              redis-rate-limiter.replenishRate: 1
              # 令牌桶最大容量
              redis-rate-limiter.burstCapacity: 2
        # 系统管理
      - id: ddx-system-manage
        uri: lb://ddx-system-manage
        predicates:
          - Path=/ddx/sys/**
        filters:
          - name: GatewayRequestRateLimiter
            args:
              # 使用SpEL名称引用Bean，与上面新建的RequestRateLimiterConfig类中的bean的name相同
              key-resolver: '#{@ipKeyResolver}'
              #令牌桶每秒填充平均速率
              redis-rate-limiter.replenishRate: 1
              # 令牌桶最大容量
              redis-rate-limiter.burstCapacity: 50
        # 数据服务
      - id: ddx-file
        uri: lb://ddx-file
        predicates:
          - Path=/ddx/file/**
        filters:
          - name: GatewayRequestRateLimiter
            args:
              # 使用SpEL名称引用Bean，与上面新建的RequestRateLimiterConfig类中的bean的name相同
              key-resolver: '#{@ipKeyResolver}'
              #令牌桶每秒填充平均速率
              redis-rate-limiter.replenishRate: 1
              # 令牌桶最大容量
              redis-rate-limiter.burstCapacity: 50
        # 日志服务
      - id: ddx-log
        uri: lb://ddx-log
        predicates:
          - Path=/ddx/log/**
        filters:
          - name: GatewayRequestRateLimiter
            args:
              # 使用SpEL名称引用Bean，与上面新建的RequestRateLimiterConfig类中的bean的name相同
              key-resolver: '#{@ipKeyResolver}'
              #令牌桶每秒填充平均速率
              redis-rate-limiter.replenishRate: 1
              # 令牌桶最大容量
              redis-rate-limiter.burstCapacity: 50
# 不校验验证码终端
ignore:
  clients:
    - test