spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: ddx123
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/ddx-auth?characterEncoding=utf-8&useSSL=false
          type: com.alibaba.druid.pool.DruidDataSource
          initialSize: 5
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          #最大超时时间 7小时
          maxEvictableIdleTimeMillis: 25200000
          validationQuery: select 1 from dual
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ddx.sys
mybatis-plus:
  #实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage: com.ddx.sys.entity
#日志监控采集配置 可参考 LogmcConfig 类的参数进行配置
ddxlog:
  monitor-collector:
    monitor-file-path: D:\\logs
    monitor-file-name: info.log
    logmc-path: D:\\JavaWork\\ddx\\ddx-system-manage\\src\\main\\resources
    isOpen: true